This is not a numpy from ground up, but I try to use all the functions that numpy provides us to perform mathematical calculations

## Internal workings of numpy

### Basics
- Written mostly in C lang and python is just a wrapper around it
- Data is stored as contigeous block of memory that can be easily cached by CPU
- Single Instruction Multiple Data paradigm used instead of Loops
- ndarray is the wrapper around chunck of memory allocated in C

### Vectorization
- Vectorization is what sppeds up numpy computations
- Instead of using python loops, numpy calls its internal C code to perform operations that involves looping 
- Uses SIMD to execute the operation parallely

### Views
- Points to same memory location but with different dimentions (ex, using reshape in numpy)

### Linear Alg in numpy
- uses BLAS and LAPACK (optimized C and Fortran program) for matrix operations
- These are heavily CPU optimized codes 
- numpy does not parallalize comps by itself, BLAS and LAPACK does it 

### C order and F order
- C order stores rows contegeously
- F order stores columns contegeouly 

``` python
import numpy as np

# C-order (default)
arr_c = np.array([[1, 2, 3],
                  [4, 5, 6]], order='C')

# Fortran-order
arr_f = np.array([[1, 2, 3],
                  [4, 5, 6]], order='F')
arr_c:
[1, 2, 3, 4, 5, 6]  # stored row-wise

arr_f:
[1, 4, 2, 5, 3, 6]  # stored column-wise
```

### How data memory is managed internally
- WHen a ndarray is created, python creates a ndarray object but only stores the metadata such as pointer to location of data
- Data is allocated a memory using c code inside and all the operations are done by c code on this data
- When this object reference count goes to 0, the memory is de-allocated by c program 

In [4]:
import numpy as np

In [ ]:
# A general comparison between python loop and numpy 

def python_dot_prod(
        a: list,
        b: list
) -> float:
    
    z = 0.

    for i in range(len(a)):
        z += a[i] * b[i]
    
    return z

a = list(range(1000))
b = list(range(1000))

%timeit python_dot_prod(a,b)

49.3 µs ± 631 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
def numpy_dot_prod(
        a: np.array,
        b: np.array
) -> float:
    
    return a.dot(b)

a = np.arange(1000)
b = np.arange(1000)

%timeit numpy_dot_prod(a,b)

1.01 µs ± 5.96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
# Workout on how to get the address of memory block the data is in and use stried to manually move in them
lst = [[1, 2, 3], 
       [4, 5, 6]]
ary2d = np.array(lst,order='C',dtype='complex64')

print(ary2d)
print(ary2d.dtype)
print(ary2d.strides)
print(ary2d.flags)
print(ary2d.shape)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
complex64
(24, 8)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

(2, 3)


In [61]:
# Construct an array

ones = np.ones((3,4),dtype='int32')
print(ones)
print(ones.strides)

zeros = np.zeros((3,4),dtype='int32')
print(zeros)

# arrays containing arbitrary values
sixtynines = np.zeros((3,4),dtype='int32') + 69
print(sixtynines)

# Identiy matrices using eye
eye = np.eye(4)
print(eye)

#linspace and ranges
ranges = np.arange(0.1,1.1,0.01)
print(ranges)

linspace = np.linspace(.5,1.5,10)
print(linspace)


# Interpolating
start_pos = np.array([0, 8])
end_pos = np.array([10, 100])

positions = np.linspace(start_pos, end_pos, num=10)
print(positions)

diag = np.diag([1,2,3])
print(diag)

eye_more = np.eye(5) + np.eye(5,k=1)
print(eye_more)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(16, 4)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23
 0.24 0.25 0.26 0.27 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37
 0.38 0.39 0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51
 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65
 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79
 0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93
 0.94 0.95 0.96 0.97 0.98 0.99 1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07
 1.08 1.09]
[0.5        0.61111111 0.72222222 0.83333333 0.94444444 1.05555556
 1.16666667 1.27777778 1.38888889 1.5       ]
[[  0.           8.        ]
 [  1.11111111  18.22222222]
 [  2.22222222  28.44444444]
 [  3.33333333  38.66666667]
 [  4.44444444  48.88888889]
 [  5.55555556  59.11111111]
 [  6.66666667  69.33

In [ ]:
# math and ufuncs
ary = np.array([[1, 2, 3], [4, 5, 6]])
ary = np.add(ary,1)
print(ary)
ary + 1 #is also possible

#custom ufuncs using numba
from numba import vectorize, guvectorize

@vectorize(['float32(float32)','float64(float64)'],target='parallel')
def non_linear(x):
    return x**2 + x**3 + 34

new_ary = non_linear(ary)

print("new ary",new_ary)
print("ary",ary)

@guvectorize(['void(float64[:,:], float64[:,:])'], '(n,m) -> (n,m)')
def reducer(x,out):
    
    for i in range(x.shape[0]):
        out[i] = x[i]

new_ary_2 = reducer(ary)
print("new ary 2",new_ary_2)

@guvectorize(['void(float64[:], float64[:], float64[:], float64[:])'], '(n),(n),()->(n)')
def scale_and_add(x, y, scalar_array, out):
    scalar = scalar_array[0]
    for i in range(x.shape[0]):
        out[i] = x[i] + scalar * y[i]

x = np.array([1., 2., 3.])
y = np.array([4., 5., 6.])
s = np.array([2.])

result = scale_and_add(x, y, s)
print(result)

print(np.std(x))
print(np.var(x))

#Broadcaasting -> dimentions can be different but never numbewr of elements in each row
print(np.array([1,2,3]) + np.array([[12,34,56],[2,3,4]]))

[[2 3 4]
 [5 6 7]]
new ary [[ 46.  70. 114.]
 [184. 286. 426.]]
ary [[2 3 4]
 [5 6 7]]
new ary 2 [[2. 3. 4.]
 [5. 6. 7.]]
[[ 9. 12. 15.]]
0.816496580927726
0.6666666666666666
[[13 36 59]
 [ 3  5  7]]


In [ ]:
# Indexing

# Normal indexing creats a view, which is just a pointer with differnt strides to orignal array
# Fancy indexsing is accesing non contegeous elements of the array and therefore creates a new array and not a view

arr = np.array([[1,2,3],
                [4,5,6]])

arr2 = arr[1] #creates a view

arr3 = arr[1].copy() #creates a copy
print(arr2)

fancy = arr[:,[0,1]] #fancy indexing, can be used for convolution 
print(fancy)

[4 5 6]
[[1 2]
 [4 5]]


Logical operators

- A: & or np.bitwise_and
- Or: | or np.bitwise_or
- Xor: ^ or np.bitwise_xor
- Not: ~ or np.bitwise_not

In [160]:
# masks

arr = np.array([[1,2,3],
                [4,5,6]])

even_mask = (arr % 2 == 0)

print(even_mask)

arr[even_mask]

# where to replace values
print(np.where(even_mask,69,0))

[[False  True False]
 [ True False  True]]
[[ 0 69  0]
 [69  0 69]]


In [ ]:
# reshape array -> creates a new view of same array

arr = np.array([[1,2,3],
                [4,5,6]])

arr_re = arr.reshape(3,2)

print(np.may_share_memory(arr,arr_re)) # confirms its a view and not copy
arr_re

print(arr.reshape(-1))
print(arr.flatten()) #view
print(arr.ravel()) #copy

True
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [156]:
# concatenating arrays

arr = np.array([[1,2,3],
                [4,5,6]])

print(np.concatenate((arr,arr),axis=0))
print(np.concatenate((arr,arr),axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
